---
name: "secret-management-ci"

"on":
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: "terraform-check"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.2"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Test
        run: terraform test
